### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by tonton1288** [CSN7841/UKSpainVisa#2]
after a date is found and the confirm booking button is pressed. i keep getting a timeout error. have i not set it up correctly or is it something else?

**Comment by CSN7841** [comment]
Give me some detail please

**Comment by tonton1288** [comment]
The script works and finds a date for an appointment. Once the page loads and I press "confirm booking" it will just get stuck on loading. Then shows a error similar to the one I attached. If it happens again I will screenshot. Not sure how else to describe the problem. 
![Cloudflare-Error-504](https://user-images.githubusercontent.com/52055155/176993044-65306251-0827-410c-a494-51780b4fc716.png)

**Comment by tonton1288** [comment]
Didn't mean to close

**Comment by CSN7841** [comment]
U can issue this again




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月2日(星期六) 下午4:28
收件人: ***@***.***&gt;; 
抄送: "????Super ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CSN7841/UKSpainVisa] timeout error (Issue #2)





 
The script works and finds a date for an appointment. Once the page loads and I press "confirm booking" it will just get stuck on loading. Then shows a error similar to the one I attached. If it happens again I will screenshot. Not sure how else to describe the problem.

**Comment by CSN7841** [comment]
What if you manually press the bottom ?
I think this problem may casued by you own network...

**Comment by tonton1288** [comment]
You mean manually without the script? That normally works but I never manage to get the slot. Shows a message that it isn't available anymore. Never shows a timeout screen.

**Comment by tonton1288** [comment]
![ukspain config](https://user-images.githubusercontent.com/52055155/176993655-5f5a7e81-e4e5-4b14-a6b7-8e570087a88a.png)
also i am suppose to change this with my own part, by logging in a account and copying the end part of the web url right?

**Comment by tonton1288** [comment]
i really appreciate your help, we are getting quite desperate here.

**Comment by CSN7841** [comment]
I have push my new code, don't need this link parameter

**Comment by tonton1288** [comment]
i have already changed it, but i will try when you update it

**Comment by CSN7841** [comment]
You can download the new code now, give it a try.

**Comment by tonton1288** [comment]
Message=not enough values to unpack (expected 5, got 4)
  Source=C:\Users\Ton\Desktop\UKSpainVisa-main\monitor.py
  StackTrace:
  File "C:\Users\Ton\Desktop\UKSpainVisa-main\monitor.py", line 29, in monitor (Current frame)
    email, password, centers, mode, date = users

**Comment by CSN7841** [comment]
My bad, date is redundant

**Comment by tonton1288** [comment]
:) ok running, let you know if i have any troubles,

**Comment by tonton1288** [comment]
It seems that when a date is found, an alert is made after the confirmation is pressed? Is it not possible to alert as soon as a date is found?

**Comment by CSN7841** [comment]
When the date was found, the alert is after the click.

**Comment by tonton1288** [comment]
I think it would make more sense if the sound is before the click? So you don't need to keep looking at the screen

**Comment by CSN7841** [comment]
This code will click for you, so you don't need to look at.

**Comment by tonton1288** [comment]
amazing job man, thank you. also what would happen if you run multiple instances of the same account in a virtual machine? would it interfere with each other?

**Comment by CSN7841** [comment]
This code has thread pool virtual machine is redundant.

**Comment by tonton1288** [comment]
i understand you can use multiple accounts but having separate scripts running at the same time at different time intervals. you should have a higher chance as it takes so long to load during each refresh. the question was logging in the same account in different instances is ok?

**Comment by CSN7841** [comment]
It is OK, but not recommend

**Comment by tonton1288** [comment]
ok found a date then this error occured. 
ERROR - Monitor runtime error from xxxxxxxxxx@gmail.com Message: Could not locate element with index -1
does this mean slot was taken?

**Comment by CSN7841** [comment]
You can try to change -1 to 1

**Comment by tonton1288** [comment]
getting this one quite often too.
ERROR - Monitor runtime error from xxxxxgmail.com Message: No element
Stacktrace:

any ideas?

**Comment by tonton1288** [comment]
getting this too when a date is found.
ERROR - Monitor runtime error from xxxx@gmail.com Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), 'Book Appointment')]"}
  (Session info: chrome=103.0.5060.66)

**Comment by CSN7841** [comment]
这些错误是因为多线程的问题找元素找不到，会自动重启的

**Comment by tonton1288** [comment]
do you think its because im running multiple instances? or unrelated?

**Comment by tonton1288** [comment]
is there any way to launch each user account  like 5 seconds apart? sorry with all the questions but i really do need to get the appointment soon, i know computers but i done know code :(

**Comment by CSN7841** [comment]
如果你是在多个虚拟机上运行，每个虚拟机只有一到两个线程，就比较稳定，如果在单个虚拟机上运行了很多线程，webdriver会因为他的竞争机制导致有时候找不页面元素，这样的话该线程下的浏览器会自动重启，目前我在尝试修复这个问题，让他更稳定，但是现在的版本确实是可以抢到的

**Comment by CSN7841** [comment]
如果要实现一个账户隔开5秒执行，也是可以的，但是我想你希望的是同步吧，不一定隔开5秒，一秒也行，就是每个线程都同步执行完一行代码之后，再执行后面的，这样会很稳定，就是速度会慢一点

**Comment by tonton1288** [comment]
ah ok i will lower the amount of accounts then, i was thinking of the account launching a few seconds apart so you can have one checking every few seconds as they take about 40-50 seconds each account to check.

**Comment by tonton1288** [comment]
I finally got a slot! Thank you very much. You got somewhere I can donate to?

**Comment by CSN7841** [comment]
Wechat CSN7841
