### ISSUE TITLE
mac m1 chromedriver unexpectedly exited

### ISSUE THREAD

**Issue by 19990715** [CSN7841/UKSpainVisa#3]
chromedriver unexpectedly exited. Status code was: -9
您好我想问下，我在mac上配置chrome driver路径后，启动程序总浏览器总是闪退，报错说chromedriver unexpectedly exited.是什么原因呢？

**Comment by CSN7841** [comment]
直接更新chrome到最新，可以不配置路径

**Comment by 19990715** [comment]
> 直接更新chrome到最新，可以不配置路径

 我更新到chrome最新后，log in的时候一直显示Google captcha verification failed. 或者Invalid credentials，麻烦问下这是人机验证时的问题吗？但是已经过了界面到登录的界面了。

谢谢

**Comment by CSN7841** [comment]
密码错误
