### ISSUE TITLE
无法预定

### ISSUE THREAD

**Issue by sulishi2011** [CSN7841/UKSpainVisa#4]
还是会被检测成机器人，自己手动在safari上反而能订上。

**Comment by CSN7841** [comment]
不可能，你没有用UC？？？？我这自动抢了好多

**Comment by sulishi2011** [comment]
用了UC，是不是频率设置太近了？

**Comment by CSN7841** [comment]
你要是偶尔被卡在外面要你验证是正常的，过一会浏览器自动重启就进去了

**Comment by sulishi2011** [comment]
不是的 就是预定就卡死 那时候明明爱丁堡有很多slot

**Comment by sulishi2011** [comment]
我知道了 还是 index -1的问题 改成1我再试试

**Comment by CSN7841** [comment]
流程是这样的：发现slot之后会自动点击，开源版本只点击一次，然后再次扫描slot。
点击之后会等网页刷新，这个很慢一般快一分钟才知道结果，点了之后没有别人快的话，网页会报个错误（时间slot也许没了），然后继续扫描slot
所以不是有就立刻抢得到

**Comment by CSN7841** [comment]
-1索引是时间slot的索引，因为每次出来的时间list都不知道有多长，自己随便设一个肯定可以包含的就行了

**Comment by CSN7841** [comment]
正确的点击逻辑很复杂，先要找到日期的slot然后如果slot有效，时间的slot就会显示，然后循环点击时间slot，所有时间选完之后再选择后面的一个日期

**Comment by sulishi2011** [comment]
好的 我再调整下试试 感谢感谢
