### ISSUE TITLE
抢不到slot

### ISSUE THREAD

**Issue by Skyfallhalo** [CSN7841/UKSpainVisa#6]
尝试用代码去刷单个人slot，三天内偶尔能发现空闲slot但一直抢不到。感觉可能是检查日期速度略慢（？）。有什么办法能提高抢到的概率吗？

ps：谢老哥分享代码。

**Comment by CSN7841** [comment]
因为太多人抢了。。。比较看运气

**Comment by Skyfallhalo** [comment]
我看到你在小步骤之间加了好多wait_for_sec(1), 如果改短会有效果以及不好的影响吗

**Comment by CSN7841** [comment]
不会
